#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00
#PBS -l vmem=30gb

singularity exec -e docker://brainlife/mcr:r2019a ./compiled/mergeROI

#make sure output exists (matlab doesn't set exit code!)
if [ ! -d output/rois ];
then
    echo "output roi folder missing"
    exit 1
fi

echo "all done"
